include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: false
    prefer_single_quotes: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_relative_imports: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    deprecated_consistency: true
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: false
    use_key_in_widget_constructors: false
    prefer_is_empty: true

    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    sized_box_for_whitespace: true
    slash_for_doc_comments: true
    unnecessary_brace_in_string_interps: true
    unnecessary_final: true
    unnecessary_new: true
    unnecessary_this: true
    void_checks: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    implementation_imports: true
    library_private_types_in_public_api: true
    lines_longer_than_80_chars: false
    no_runtimeType_toString: true
    non_constant_identifier_names: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_double_quotes: false
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_null_operators: true

