name: Tiba_Gates
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  numberpicker: ^2.1.1
  camera:
  flutter_image_compress: ^1.0.0
  shared_preferences: ^2.0.5
  screenshot: ^1.2.3
  google_fonts: ^1.1.2
  flutter_launcher_icons:
  flutter_screenutil: ^5.0.1+2
  pull_to_refresh: null
  animate_do: ^2.0.0
  auto_size_text: ^3.0.0
  bordered_text: ^2.0.0
  flutter_udid:
  charset_converter: ^2.1.0
  permission_handler: ^6.1.1
  expandable: ^5.0.1
  share: ^2.0.1
  share_plus: ^2.1.4
  image_picker:
  transparent_image: ^1.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bluetooth_basic: ^0.1.5

  flutter_svg:
  fluttertoast: ^8.0.8
  #esc_pos_bluetooth: ^0.1.0
  get_it:
  connectivity: ^3.0.6
  font_awesome_flutter: ^9.2.0
  lottie:
  path_provider:
  intl: ^0.17.0
  bluetooth_print: ^2.0.0
  dotted_decoration: ^2.0.0
  #esc_pos_printer: ^4.0.3
  esc_pos_bluetooth: ^0.2.8

  syncfusion_flutter_datepicker: ^19.4.55
  logger: ^1.1.0
  flutter_slidable: ^0.6.0
  provider: ^6.0.1
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  url_launcher:
  get: ^3.25.5
  flutter_bluetooth_serial: ^0.4.0
  syncfusion_flutter_sliders: ^19.4.56

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tipasplash.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages